ALERT-PREFIX: "&9&lPandaAnnouncement"

WHOIS-MESSAGE:
  - '&f&m-----------------------------'
  - '&3&lServerName &7- &fInformation the &b%name%'
  - ' '
  - '&3Uuid: &f%uuid%'
  - '&3Custom Name: &f%customname%'
  - '&3Server: &f%server%'
  - '&3Ip: &f%ip%'
  - '&3Ping: &f%ping%'
  - '&3Perms: &f%perms%'
  - '&f&m-----------------------------'

MOTD-EDIT: "%D_ARROW%&4Panda Development Mode %NEWLINE% Bungee Mode Active"

SERVER:
  build:
    PERMS: "nucleus.build"
  kitmap:
    PERMS: "nucleus.kitmap"



