# General Config
ALERT-PREFIX: "&9&lPandaAnnouncement"
NO-PERMISSIONS: ""
CONSOLE-EXECUTE: ""
STAFF:
  CHAT-FORMAT: "&3[%server%] %prefix% %name%: %message% "
  JOIN: "&3[Staff] %prefix% %name% has join to %server%"
  LEAVE: "&3[Staff] %prefix% %name% has leave to %server%"
  DISCONNECT: "&9[Staff] %prefix% %name% &bhas disconnected from the Network!"
MESSAGE:
  PING: "Your ping is %ping%"
  PING-TARGET: "%name% ping is %ping"

WHOIS-MESSAGE:
  - '&f&m-----------------------------'
  - '&3&lServerName &7- &fInformation the &b%name%'
  - ' '
  - '&3Uuid: &f%uuid%'
  - '&3Custom Name: &f%customname%'
  - '&3Server: &f%server%'
  - '&3Ip: &f%ip%'
  - '&3Ping: &f%ping%'
  - '&3Perms: &f%perms%'
  - '&3Rank: %rank%'
  - '&f&m-----------------------------'
  #Remove if you want or add line if you want
MOTD:
  STATUS: true
  MOTD-EDIT: "%D_ARROW%&4Panda Development %NEWLINE% discord.gg/pandacomunnity"
MAINTENACE:
  MOTD:
    STATUS: false
    MOTD-EDIT: "%D_ARROW%&4Panda Development %NEWLINE% Maintenance Mode Active"
  PING:
    ENABLE: false
    PING-EDIT: "&cWHITELIST"
  KICK_MESSAGE: "&cServer in Maintenance Mode %NEWLINE% Need Support? Join discord.gg/pandacomunnity"
SERVER:
  build:
    PERMS: "nucleus.build"
  hcf:
    PERMS: "nucleus.hcf"
  practice:
    PERMS: "nucleus.practice"
  hub:
    PERMS: "nucleus.hub"





