ALERT-PREFIX: "&9&lPandaAnnouncement"

WHOIS-MESSAGE:
  - '&f&m-----------------------------'
  - '&3&lServerName &7- &fInformation the &b%name%'
  - ' '
  - '&3Uuid: &f%uuid%'
  - '&3Custom Name: &f%customname%'
  - '&3Server: &f%server%'
  - '&3Ip: &f%ip%'
  - '&3Ping: &f%ping%'
  - '&3Perms: &f%perms%'
  - '&3Rank: %rank%'
  - '&f&m-----------------------------'
  #Remove if you want or add line if you want
MOTD:
  STATUS: true
  MOTD-EDIT: "%D_ARROW%&4Panda Development %NEWLINE% discord.gg/pandacomunnity"
MAINTENANCE-MOTD:
  STATUS: false
  MOTD-EDIT: "%D_ARROW%&4Panda Development %NEWLINE% Maintenance Mode Active"

SERVER:
  build:
    PERMS: "nucleus.build"
  hcf:
    PERMS: "nucleus.hcf"
  practice:
    PERMS: "nucles.practice"

BLOCK-COMMAND:
  COMMAND:
    - 'bukkit:op'
    - '/op'

MAINTENACE:
  ENABLE: false
  PING: "&cWHITELIST"
  KICK_MESSAGE: "&cServer in Maintenance Mode %NEWLINE% Need Support? Join discord.gg/pandacomunnity"



