# General Config
ALERT-PREFIX: "&9&lPandaAnnouncement"
PING-COMMAND:
  STATUS: false
NO-PERMS: "&cYou dont have permissions!"
STAFF:
  JOIN: "&3[Staff] %prefix% %name% has join to %server%"
  LEAVE: "&3[Staff] %prefix% %name% has leave to %server%"
  REPORT:
    - "&9[Report] [%server%] %prefix% %name% &bhas reported &a %player_report%"
    - "&aReasons: &b %reasons%"
  REQUEST:
    - "&9[Request] [%server%] %prefix% %name% &bhas request help!"
    - "&aReasons: &b %reasons%"
MESSAGE:
  PING: "Your ping is %ping%"
  PING-TARGET: "%name% ping is %ping%"

WHOIS-MESSAGE:
  - '&f&m-----------------------------'
  - '&3&lServerName &7- &fInformation the &b%name%'
  - ' '
  - '&3Uuid: &f%uuid%'
  - '&3Custom Name: &f%customname%'
  - '&3Server: &f%server%'
  - '&3Ip: &f%ip%'
  - '&3Ping: &f%ping%'
  - '&3Perms: &f%perms%'
  - '&3Rank: %rank%'
  - '&3Location: %location%'
  - '&f&m-----------------------------'
  #Remove if you want or add line if you want
MOTD:
  STATUS: false
  MOTD-EDIT: "%D_ARROW%&4Panda Development %NEWLINE% discord.gg/pandacomunnity"
MAINTENACE:
  MOTD:
    STATUS: false
    MOTD-EDIT: "%D_ARROW%&4Panda Development %NEWLINE% Maintenance Mode Active"
  PING:
    ENABLE: false
    PING-EDIT: "&cWHITELIST"
  KICK_MESSAGE: "&cServer in Maintenance Mode %NEWLINE% Need Support? Join discord.gg/pandacomunnity"
SERVER-MESSAGE: "&cConnect to %server%"
SERVER:
  build:
    PERMS: "nucleus.build"
  hcf:
    PERMS: "nucleus.hcf"
  practice:
    PERMS: "nucleus.practice"
  hub:
    PERMS: "nucleus.hub"

ANUNCIOS:
  STATUS: true
  COOLDOWN: 1 # MINUTOS SOLO
  ANUNCIOS_ACTIVADOS:
    - ANUNCIO1
    - ANUNCIO2
  ANUNCIOS:
    ANUNCIO1:
      MENSAJE: '&fYou can edit this | on config.yml %NEWLINE%'
    ANUNCIO2:
      MENSAJE: '&fYou can edit this | on config.yml %D_ARROW%'

CHAT:
  STAFF:
    FORMAT:
      - "&3[%server%] %ranks% %name%: %message%"
    PERMS: "nucleus.staffchat"
    ENABLE-CHAT: "&cStaff chat enable"
    DISABLE-CHAT: "&cStaff chat disable"
  VIP:
    FORMAT:
      - "&3[%server%] %ranks% %name%: %message%"
    PERMS: "nucleus.vipchat"
    ENABLE-CHAT: "&cVIP chat enable"
    DISABLE-CHAT: "&cVIP chat disable"
    JOIN:
      STATUS: true
      MESSAGE: "&4[VIP] %prefix% %name% has join to the server"






